"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Repository = exports.Column = exports.PrimaryColumn = exports.Entity = void 0;
var Entity_1 = require("./decorate/Entity");
Object.defineProperty(exports, "Entity", { enumerable: true, get: function () { return Entity_1.Entity; } });
var PrimaryColumn_1 = require("./decorate/PrimaryColumn");
Object.defineProperty(exports, "PrimaryColumn", { enumerable: true, get: function () { return PrimaryColumn_1.PrimaryColumn; } });
var Column_1 = require("./decorate/Column");
Object.defineProperty(exports, "Column", { enumerable: true, get: function () { return Column_1.Column; } });
var Repository_1 = require("./decorate/util/Repository");
Object.defineProperty(exports, "Repository", { enumerable: true, get: function () { return Repository_1.Repository; } });
